changesin yml4

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -10,28 +10,16 @@ env:
 
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: windows-latest
     steps:
     - name: Checkout repo
       uses: actions/checkout@v2.3.4
 
-    - name: Install Astronomer CLI
-      run: |
-        wget -qO- https://get.astronomer.io | bash
-        echo "$HOME/.astro/bin" >> $GITHUB_PATH
-        # Check if the installation succeeded
-        ls -la $HOME/.astro/bin
-
     - name: Verify Astronomer CLI Installation
       run: |
-        echo 'PATH=$HOME/.astro/bin:$PATH' >> $GITHUB_ENV
-        source $GITHUB_ENV
-        which astro || echo "astro not found"
-        astro --version || echo "Failed to get astro version"
+        echo "Checking if Astronomer CLI is installed..."
+        where astro.exe || echo "astro.exe not found"
 
     - name: Deploy to Astro
       run: |
-        source $GITHUB_ENV
-        astrocloud deploy --pytest ${{ secrets.ASTRONOMER_DEPLOYMENT_ID_DEV }}
-      env:
-        ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN_DEV }}
+        astro cloud deploy --pytest ${{ secrets.ASTRONOMER_DEPLOYMENT_ID_DEV }}
